# Generated by Django 3.1.7 on 2021-04-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210402_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhonesCategory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('display', models.CharField(max_length=255, verbose_name='Дисплей')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('sd', models.BooleanField()),
                ('memory', models.CharField(max_length=255, verbose_name='Память')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип экрана')),
                ('phone_core', models.CharField(default=None, max_length=255, verbose_name='Процессор')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
            bases=('store.product',),
        ),
        migrations.AlterModelOptions(
            name='laptopscategory',
            options={'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.RemoveField(
            model_name='laptopscategory',
            name='nameww',
        ),
        migrations.AddField(
            model_name='laptopscategory',
            name='core',
            field=models.CharField(default=1, max_length=255, verbose_name='Процессор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopscategory',
            name='disk_memory',
            field=models.CharField(default=None, max_length=255, verbose_name='Память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopscategory',
            name='display',
            field=models.CharField(default=None, max_length=255, verbose_name='Дисплей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopscategory',
            name='lap_ram',
            field=models.CharField(default=None, max_length=255, verbose_name='Оперативаня память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopscategory',
            name='video_adapter',
            field=models.CharField(default=None, max_length=255, verbose_name='Видеокарта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
    ]
