# Generated by Django 3.1.7 on 2021-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_user', '0002_auto_20210331_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
