# Generated by Django 3.1.7 on 2021-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_user', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
