# Generated by Django 3.1.7 on 2021-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_user', '0006_auto_20210331_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
