# Generated by Django 3.1.7 on 2021-04-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_user', '0007_auto_20210402_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
