# Generated by Django 3.1.7 on 2021-08-04 17:33

import c_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_user', '0008_auto_20210402_1431'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', c_user.models.MyUserManager()),
            ],
        ),
    ]
